require("conf.options")
require("conf.keymaps")
require("conf.init_lazy")
require("conf.autocmds")
require("conf.lsp.keymaps").setup()
require("conf.lang.c").setup()
require("conf.lang.zig").setup()
require("conf.lang.go").setup()
